from typing import Any, TypedDict


class GraphState(TypedDict):

    # Original user message
    message: str

    # Execution plan generated by Supervisor
    plan: list[str]

    # Current interaction
    interaction: dict[str, Any]

    # Search results
    search_results: list

    # AI outputs
    summary: str
    medical_insights: str
    recommendations: str

    # Tool execution status
    tool_result: str

    # Database ID after save
    saved_id: int

    # Final response returned to frontend
    final_response: dict[str, Any]